export const UPDATE_GLOBAL_INFO = 'UPDATE_GLOBAL_INFO'

export const UPDATE_MENU_STATUS = 'UPDATE_MENU_STATUS'

export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'

export const UPDATE_ARTICLE_LIST = 'UPDATE_ARTICLE_LIST'

export const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL'

export const SET_TOTAL_PAGE = 'SET_TOTAL_PAGE'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SET_PAGE_DETAIL = 'SET_PAGE_DETAIL'

export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'

export const SET_COMMENT_TOTAL = 'SET_COMMENT_TOTAL'

export const RESET_COMMENT = 'RESET_COMMENT'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const UPDATE_COMMENT_OPINION = 'UPDATE_COMMENT_OPINION'

export const SET_EXPRESSION = 'SET_EXPRESSION'

export const UPDATE_VIEW_COUNT = 'UPDATE_VIEW_COUNT'

export const UPDATE_OPINION = 'UPDATE_OPINION'

export const UPDATE_OPINION_LOADING = 'UPDATE_OPINION_LOADING'
